### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-AndreLuna6#1]
[Infografia2_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-AndreLuna6/files/8684207/Infografia2_AndreEmmanuelLunaGonzalez.pdf)

**Comment by Rmz-Rigo** [comment]
Calificación: 17/20

-Partes de una infografía: 4
-Coherencia y pertenencia: 2, no tiene las fuentes.
-Organización de 
la información: 4
-Diseño y 
composición de 
la infografía: 3
-Creatividad: 4

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
